### ISSUE TITLE
No comment is posted on the PR

### ISSUE THREAD

**Issue by revolter** [devblackops/github-action-psscriptanalyzer#14]
I used this config:

```yml
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Lint 🕵🏻‍♂️
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
```

and even though it finds:

![image](https://user-images.githubusercontent.com/5748627/109066857-5c72ec80-76f6-11eb-8c5c-8b603b3cd26f.png)

no comment is posted on the PR.
